name: Deploy CDK

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.APP_AWS_REGION }}

      - name: Install dependencies
        working-directory: aws-cdk
        run: npm ci

      - name: Build CDK app
        working-directory: aws-cdk
        run: npm run build

      - name: Synthesize
        working-directory: aws-cdk
        run: npm run synth

      - name: Deploy
        working-directory: aws-cdk
        env:
          CDK_DEFAULT_REGION: ${{ secrets.APP_AWS_REGION }}
        run: npm run deploy -- -y


